apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "04.09.55"
          url: "docker.io/cbpautomation/python-hello-world-docker:04.09.55"
          digest: "sha256:a296457a4329b0b2f3043b2ea86623fd8487ffa09c7915d2c22ee5848208ca65"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          target-environment: QA
          artifact-id: ${{ steps.register.outputs.artifact-id }}
      - name: add_labels_to_artifact_version
        uses: cloudbees-io/label-artifact-version@v1
        with:
          artifact-id: ${{ steps.register.outputs.artifact-id }}
          labels: ready-to-test, ready-to-deploy
