apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "29.09.37"
          url: "docker.io/cbpautomation/python-hello-world-docker:29.09.37"
          digest: "sha256:fadb8dc50a3f3c74a80d6608172966f30c473715fc4d803eb7dd6ae0aace0daa"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          target-environment: QA
          artifact-id: ${{ steps.register.outputs.artifact-id }}
      - name: add_labels_to_artifact_version
        uses: cloudbees-io/label-artifact-version@v1
        with:
          artifact-id: ${{ steps.register.outputs.artifact-id }}
          labels: ready-to-test, ready-to-deploy
