apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "19.00.02"
          url: "docker.io/cbpautomation/python-hello-world-docker:19.00.02"
          digest: "sha256:4bd815d7f2dab5260668c2670e47a909913ed8430ee980d18096f1ab482c7c45"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "QA"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

