apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "01.12.39"
          url: "docker.io/cbpautomation/python-hello-world-docker:01.12.39"
          digest: "sha256:37cc5f6fa60c62a02915159072b3e7b4ca67a05b39033820751e4eb6dd6054a5"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "QA"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

