apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "12.23.56"
          url: "docker.io/cbpautomation/python-hello-world-docker:12.23.56"
          digest: "sha256:f9d9fff8632d502976bc880ea06b32c2c7269fe0a25a447c81fd2f32cf848b5b"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "QA"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

