apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "22.10.49"
          url: "docker.io/cbpautomation/python-hello-world-docker:22.10.49"
          digest: "sha256:1da3052d3fa3d78af78998d3324022184d94f2926c00a0a41c02c105b35acbc9"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "QA"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

