apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v1
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "13.23.53"
          url: "docker.io/cbpautomation/python-hello-world-docker:13.23.53"
          digest: "sha256:9744d492c120dfa773f350d8fda08ae85f673767002b05f10c99751499e62d6d"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "QA"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

