apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RegisterDeployedArtifact
on:
  workflow_dispatch:
jobs:
  env_reg_artifacts:
    steps:
      - name: Inform system that an artifact version was created
        uses: cloudbees-io/register-build-artifact@v2
        id: register
        with:
          name: "cbpautomation/python-hello-world-docker"
          version: "01.13.58"
          url: "docker.io/cbpautomation/python-hello-world-docker:01.13.58"
          digest: "sha256:60bf906e6f9832ac2b6c0b9a5d38233eb03a022be76fa7ce33ca53024afd0f2a"
          
      - name: success_valid_env_reg_artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: allPassed, deployed
          target-environment: "QA"
          artifact-id: ${{ steps.register.outputs.artifact-id }}

